### ISSUE TITLE
Taking energy>1 in covariance kernels fails 

### ISSUE THREAD

**Issue by solbes** [malmgrek/gammy#5]
Sometimes one would like to use the full basis in the computation (e.g. some illustration) and not use the dimension reduction trick. Setting `energy > 1` should give you all the basis functions, but this fails, since some of the eigenvalues returned by `np.linalg.eigh` are negative for some reason (very small negative numbers). Using `np.linalg.svd` instead would solve the issue.

**Comment by malmgrek** [comment]
You're right, this is a good point. I will implement the suggested changes.

**Comment by malmgrek** [comment]
Actually I think the main problem is not failing to return absolutely all basis functions. In the code `w` denote the eigenvalues of `A` which is a symmetric positive-definite (covariance) matrix. The truncated eigenvectors are selected according to the condition `w.cumsum() / w.sum() <= energy`. Even if the array `w` (erroneously) has some negative values, we would still get all eigenvectors with e.g. `energy=1.01` since the array `w` is ascending (as returned by `np.linalg.eigh`). 

However, I think a true problem is that setting `energy=0` does not guarantee we get zero eigenvectors which, I guess, is natural to expect.

**Comment by malmgrek** [comment]
This is now fixed. Closing the issue.
